//////////////////////////////////////////////////////////////////
// 文件名：AICorpusManager.swift
// 文件说明：本地动态 RAG 语料管理与 AI 带教系统核心模块 (完美回放版)
// 功能说明：包含数据模型、NLP极速语义检索、Teacher-Student录制合成与 UI 管理面板
// 进阶升级：支持 TargetID 徽标、动作流列表显示、按序回放与 UI 同步高亮、快捷键删除、探针卸载
// [✨增强]：支持列表编辑、TargetID序号展示、等待节点插入、自动滚动跟踪、输入显隐化、一键停止录制
// 代码要求：请保证代码的逻辑和完整性，保留代码中的所有注释内容
//////////////////////////////////////////////////////////////////

import SwiftUI
import AppKit
import NaturalLanguage
import Foundation
import Combine
import UniformTypeIdentifiers

// MARK: - 1. 数据模型与自愈机制 (Teacher-Student & 达尔文机制)
struct WebCorpusRecord: Codable, Identifiable, Equatable {
    let id: UUID
    let timestamp: Date
    
    var userIntent: String
    var beforeDOM: String
    var actionType: String
    var targetId: String
    var inputValue: String?
    
    var synthesizedThought: String?
    var synthesizedStepsJSON: String?
    
    var successCount: Int = 0
    var failCount: Int = 0
    
    // [✨修改点3.1]：语料库分组与来源标识
    var groupName: String = "默认分组"
    var isAutoGenerated: Bool = false
    
    var totalUsed: Int { successCount + failCount }
    
    var reliabilityStatus: String {
        if totalUsed == 0 { return "🆕 新录制" }
        let rate = Double(successCount) / Double(totalUsed)
        if totalUsed >= 3 && rate < 0.4 { return "⚠️ 建议废弃" }
        if totalUsed >= 2 && rate > 0.8 { return "⭐️ 高可靠" }
        return "✅ 可用 (\(Int(rate * 100))%)"
    }
    
    var reliabilityWeight: Double {
        if totalUsed == 0 { return 1.0 }
        let rate = Double(successCount) / Double(totalUsed)
        if totalUsed >= 3 && rate < 0.4 { return 0.1 }
        return 0.5 + (0.5 * rate)
    }
    
    // 自定义初始化方法，保证兼容旧数据 JSON 结构
    init(id: UUID, timestamp: Date, userIntent: String, beforeDOM: String, actionType: String, targetId: String, inputValue: String? = nil, synthesizedThought: String? = nil, synthesizedStepsJSON: String? = nil, successCount: Int = 0, failCount: Int = 0, groupName: String = "默认分组", isAutoGenerated: Bool = false) {
        self.id = id; self.timestamp = timestamp; self.userIntent = userIntent; self.beforeDOM = beforeDOM; self.actionType = actionType; self.targetId = targetId; self.inputValue = inputValue; self.synthesizedThought = synthesizedThought; self.synthesizedStepsJSON = synthesizedStepsJSON; self.successCount = successCount; self.failCount = failCount; self.groupName = groupName; self.isAutoGenerated = isAutoGenerated
    }
    
    enum CodingKeys: String, CodingKey {
        case id, timestamp, userIntent, beforeDOM, actionType, targetId, inputValue, synthesizedThought, synthesizedStepsJSON, successCount, failCount, groupName, isAutoGenerated
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        timestamp = try container.decode(Date.self, forKey: .timestamp)
        userIntent = try container.decode(String.self, forKey: .userIntent)
        beforeDOM = try container.decode(String.self, forKey: .beforeDOM)
        actionType = try container.decode(String.self, forKey: .actionType)
        targetId = try container.decode(String.self, forKey: .targetId)
        inputValue = try container.decodeIfPresent(String.self, forKey: .inputValue)
        synthesizedThought = try container.decodeIfPresent(String.self, forKey: .synthesizedThought)
        synthesizedStepsJSON = try container.decodeIfPresent(String.self, forKey: .synthesizedStepsJSON)
        successCount = try container.decodeIfPresent(Int.self, forKey: .successCount) ?? 0
        failCount = try container.decodeIfPresent(Int.self, forKey: .failCount) ?? 0
        groupName = try container.decodeIfPresent(String.self, forKey: .groupName) ?? "默认分组"
        isAutoGenerated = try container.decodeIfPresent(Bool.self, forKey: .isAutoGenerated) ?? false
    }
}

// MARK: - 2. NLP 极速语义检索数据库 (RAG Core)
class CorpusDatabase: ObservableObject {
    static let shared = CorpusDatabase()
    
    private let fileURL: URL
    @Published var records: [WebCorpusRecord] = []
    
    init() {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        self.fileURL = docs.appendingPathComponent("rpa_corpus.json")
        self.load()
    }
    
    func load() {
        guard let data = try? Data(contentsOf: fileURL),
              let decoded = try? JSONDecoder().decode([WebCorpusRecord].self, from: data) else {
            self.records = []
            return
        }
        self.records = decoded
    }
    
    func save() {
        if let data = try? JSONEncoder().encode(records) {
            try? data.write(to: fileURL)
        }
    }
    
    func addRecord(_ record: WebCorpusRecord) {
        records.append(record)
        save()
    }
    
    func reportExecutionResult(id: UUID, isSuccess: Bool) {
        DispatchQueue.main.async {
            guard let index = self.records.firstIndex(where: { $0.id == id }) else { return }
            if isSuccess {
                self.records[index].successCount += 1
            } else {
                self.records[index].failCount += 1
            }
            self.save()
        }
    }
    
    private func extractKeywords(from text: String) -> Set<String> {
        let tagger = NLTagger(tagSchemes: [.lexicalClass])
        tagger.string = text
        var keywords = Set<String>()
        let options: NLTagger.Options = [.omitPunctuation, .omitWhitespace, .omitOther, .joinNames]
        
        tagger.enumerateTags(in: text.startIndex..<text.endIndex, unit: .word, scheme: .lexicalClass, options: options) { tag, tokenRange in
            if let tag = tag, tag == .noun || tag == .verb || tag == .organizationName || tag == .adjective || tag == .placeName {
                let word = String(text[tokenRange]).lowercased()
                if word.count > 0 { keywords.insert(word) }
            }
            return true
        }
        return keywords.isEmpty ? Set(text.lowercased().map { String($0) }) : keywords
    }
    
    func searchTopRelevantAdvanced(intent: String, topK: Int = 2) -> [WebCorpusRecord] {
        guard !records.isEmpty else { return [] }
        let targetKeywords = extractKeywords(from: intent)
        if targetKeywords.isEmpty { return [] }
        
        let scoredRecords = records.compactMap { record -> (record: WebCorpusRecord, score: Double)? in
            if record.reliabilityWeight <= 0.2 { return nil }
            let recordKeywords = extractKeywords(from: record.userIntent)
            let intersection = targetKeywords.intersection(recordKeywords)
            let baseScore = Double(intersection.count) / Double(targetKeywords.union(recordKeywords).count)
            let finalScore = baseScore * record.reliabilityWeight
            return (record, finalScore)
        }
        
        return scoredRecords.filter { $0.score > 0.15 }
                            .sorted { $0.score > $1.score }
                            .prefix(topK)
                            .map { $0.record }
    }
    
    func exportForFineTuning() -> String {
        var jsonl = ""
        for record in records {
            guard let thought = record.synthesizedThought, let steps = record.synthesizedStepsJSON else { continue }
            if record.reliabilityWeight <= 0.2 { continue }
            
            let sys = "你是一个网页自动化助手。请结合可见元素列表，决定下一步操作。"
            let usr = "【任务】: \(record.userIntent)\\n【DOM】:\\n\(record.beforeDOM)"
            let ast = "{\\n  \"thought\": \"\(thought)\",\\n  \"steps\": \(steps)\\n}"
            
            let safeAst = ast.replacingOccurrences(of: "\n", with: "\\n")
                             .replacingOccurrences(of: "\"", with: "\\\"")
            
            jsonl += "{\"messages\": [{\"role\": \"system\", \"content\": \"\(sys)\"}, {\"role\": \"user\", \"content\": \"\(usr)\"}, {\"role\": \"assistant\", \"content\": \"\(safeAst)\"}]}\n"
        }
        return jsonl
    }
}

// MARK: - 3. 语料录制与云端大模型数据清洗引擎
class WebCorpusManager: ObservableObject {
    static let shared = WebCorpusManager()
    
    private var pollTimer: Timer?
    private var globalEventMonitor: Any? // 全局热键监听器
    
    @Published var isRecordingMode: Bool = false {
        didSet {
            if isRecordingMode {
                startPollingExternalBrowsers()
                setupHotkeys()
            } else {
                stopPollingExternalBrowsers()
                removeHotkeys()
                Task { await stopAndTeardownProbe() }
                sessionEvents.removeAll()
                currentUserIntent = ""
                playingEventId = nil
            }
        }
    }
    @Published var currentUserIntent: String = ""
    @Published var isPaused: Bool = false {
        didSet {
            let status = isPaused ? "已暂停录制 (⌥⌘R 继续)" : "录制中 (⌥⌘R 暂停)"
            AgentMonitorManager.shared.actionExecutionLogs.append("⏸ \(status)")
        }
    }
    @Published var playingEventId: UUID? = nil
    
    struct RawSessionEvent: Identifiable {
        let id = UUID()
        var actionType: String
        var targetId: String
        var inputValue: String?
        var elementText: String
        var domSummary: String
        var isSecureInput: Bool = false
    }
    @Published var sessionEvents: [RawSessionEvent] = []
    
    // MARK: - 热键与生命周期管理
    private func setupHotkeys() {
        let handler: (NSEvent) -> Void = { [weak self] event in
            if event.modifierFlags.contains([.command, .option]) && event.keyCode == 15 { // 15 是 'R' 键
                DispatchQueue.main.async { self?.isPaused.toggle() }
            }
        }
        globalEventMonitor = NSEvent.addGlobalMonitorForEvents(matching: .keyDown, handler: handler)
        NSEvent.addLocalMonitorForEvents(matching: .keyDown) { event in
            if event.modifierFlags.contains([.command, .option]) && event.keyCode == 15 {
                DispatchQueue.main.async { self.isPaused.toggle() }
                return nil
            }
            return event
        }
    }
    
    private func removeHotkeys() {
        if let monitor = globalEventMonitor {
            NSEvent.removeMonitor(monitor)
            globalEventMonitor = nil
        }
    }
    
    func stopRecording() {
        self.isRecordingMode = false // 触发 didSet 里的清理逻辑
        AgentMonitorManager.shared.actionExecutionLogs.append("⏹ 已停止录制并向浏览器发送探针卸载指令。")
    }
    
    // [✨修复 1] 完善停止录制与界面闭环，隐藏HUD并恢复系统焦点
    func closeRecording() {
        self.isRecordingMode = false
        AgentMonitorManager.shared.actionExecutionLogs.append("⏹ 已停止录制并卸载网页探针。")
        
        DispatchQueue.main.async {
            // 1. 关闭悬浮窗口
            CorpusHUDManager.shared.hideHUD()
            
            // 2. 智能定位并唤起 RPA 相关的核心窗口（优先唤醒语料库，其次是主流程面板）
            let windowsToActivate = NSApp.windows.filter {
                $0.title == "AI 动作经验库 (本地 RAG)" ||
                $0.title == "我的流程" ||
                $0.className.contains("AppKitWindow")
            }
            
            if let targetWindow = windowsToActivate.first(where: { $0.title == "AI 动作经验库 (本地 RAG)" }) ?? windowsToActivate.first {
                targetWindow.makeKeyAndOrderFront(nil)
            }
            
            // 3. 强行夺回系统级焦点
            NSApp.activate(ignoringOtherApps: true)
        }
    }
    
    @MainActor
    func addWaitAction(seconds: Double = 1.0) {
        let waitEvent = RawSessionEvent(actionType: "wait", targetId: "", inputValue: "\(seconds)", elementText: "强制延时 \(seconds) 秒", domSummary: "")
        sessionEvents.append(waitEvent)
        AgentMonitorManager.shared.actionExecutionLogs.append("⏳ 已在动作流中插入等待 \(seconds) 秒节点")
    }
    
    // MARK: - 外部浏览器轮询机制
    private func startPollingExternalBrowsers() {
        pollTimer?.invalidate()
        pollTimer = Timer.scheduledTimer(withTimeInterval: 0.8, repeats: true) { [weak self] _ in
            Task { await self?.pollActiveBrowser() }
        }
    }
    
    private func stopPollingExternalBrowsers() {
        pollTimer?.invalidate()
        pollTimer = nil
    }

    @MainActor
    private func stopAndTeardownProbe() async {
        let targetBrowser = getTargetBrowser()
        _ = BrowserScriptBridge.runJS(in: targetBrowser, js: BrowserScriptBridge.probeTeardownJS)
    }
    
    // [✨修复 3A] 防止录制回放时定位迷失，识别 RPA 自身的 InternalBrowser
    private func getTargetBrowser() -> String {
        guard let appName = NSWorkspace.shared.frontmostApplication?.localizedName else { return "Google Chrome" }
        // 识别出当前应用正是此 RPA 程序自己时，返回内建浏览器标识
        if appName == ProcessInfo.processInfo.processName { return "InternalBrowser" }
        return appName == "Safari" ? "Safari" : "Google Chrome"
    }

    // [✨修复点2] 动态加入探针，并解决页面跳转刷新问题
    @MainActor
    private func pollActiveBrowser() async {
        guard isRecordingMode else { return }
        let targetBrowser = getTargetBrowser()
        
        // 【探测脚本】检查全局标志位，如果有数据就带出来，没有探针就返回特定标识
        let pullScript = """
        (function() {
            if(window._rpaCorpusInjected) { 
                let res = JSON.stringify(window._rpaEventBuffer || []); 
                window._rpaEventBuffer = []; 
                return res; 
            } else { return 'NOT_INJECTED'; }
        })();
        """
        
        let jsonString = BrowserScriptBridge.runJS(in: targetBrowser, js: pullScript)
        
        if jsonString == "NOT_INJECTED" {
            // 如果返回 NOT_INJECTED，说明页面是新打开的、或者刚发生了跳转刷新，导致探针丢失
            // 此时动态执行注入脚本
            _ = BrowserScriptBridge.runJS(in: targetBrowser, js: BrowserScriptBridge.probeInjectionJS)
            AgentMonitorManager.shared.actionExecutionLogs.append("💉 检测到页面加载，已动态注入 RPA 探针")
            
        } else if let jsonString = jsonString, jsonString != "[]" && jsonString != "NOT_FOUND" {
            if isPaused { return } // 暂停状态丢弃数据
            
            if let data = jsonString.data(using: .utf8), let events = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]] {
                for dict in events {
                    let eventType = dict["event"] as? String ?? "unknown"
                    let targetId = dict["target_id"] as? String ?? ""
                    if targetId.isEmpty { continue }
                    
                    let newEvent = RawSessionEvent(
                        actionType: eventType,
                        targetId: targetId,
                        inputValue: dict["input_value"] as? String,
                        elementText: (dict["element_text"] as? String ?? "").isEmpty ? "未知元素" : (dict["element_text"] as! String),
                        domSummary: dict["dom_summary"] as? String ?? ""
                    )
                    sessionEvents.append(newEvent)
                    AgentMonitorManager.shared.actionExecutionLogs.append("📸 已记录: [\(eventType)] -> \(newEvent.elementText)")
                }
            }
        }
    }
    
    // MARK: - 🎯 核心通信：接收 BrowserView 内部浏览器事件回调
    @MainActor
    func handleWebEvent(browser: String, eventType: String, value: String? = nil, elementText: String = "", domSummary: String, targetId: String) async {
        guard isRecordingMode, !isPaused else { return }
        guard !targetId.isEmpty else { return }
        
        let newEvent = RawSessionEvent(
            actionType: eventType,
            targetId: targetId,
            inputValue: value,
            elementText: elementText.isEmpty ? "未知元素" : elementText,
            domSummary: domSummary
        )
        
        sessionEvents.append(newEvent)
        AgentMonitorManager.shared.actionExecutionLogs.append("📸 内置捕捉: [\(eventType)] -> \(newEvent.elementText)")
    }
    
    // MARK: - 动作回放与管理
    @MainActor
    func playbackAction(event: RawSessionEvent) async {
        if event.targetId.isEmpty { return }
        let targetBrowser = getTargetBrowser()
        let js = BrowserScriptBridge.generatePlaybackJS(targetId: event.targetId, actionType: event.actionType, inputValue: event.inputValue ?? "")
        _ = BrowserScriptBridge.runJS(in: targetBrowser, js: js)
    }
    
    @MainActor
    func playAllActions() async {
        guard !sessionEvents.isEmpty else { return }
        let wasPaused = isPaused
        isPaused = true
        
        // [✨修改点4.1] 回放前增加 3 秒倒计时等待
        AgentMonitorManager.shared.actionExecutionLogs.append("⏳ 准备回放，等待 3 秒钟确保页面就绪...")
        for i in (1...3).reversed() {
            AgentMonitorManager.shared.actionExecutionLogs.append("⏳ \(i)...")
            try? await Task.sleep(nanoseconds: 1_000_000_000)
        }
        
        for event in sessionEvents {
            playingEventId = event.id
            AgentMonitorManager.shared.actionExecutionLogs.append("▶️ 正在回放动作: \(event.elementText)")
            if event.actionType == "wait" {
                let secs = Double(event.inputValue ?? "1") ?? 1.0
                try? await Task.sleep(nanoseconds: UInt64(secs * 1_000_000_000))
            } else {
                await playbackAction(event: event)
                try? await Task.sleep(nanoseconds: 1_200_000_000)
            }
        }
        
        playingEventId = nil
        isPaused = wasPaused
        AgentMonitorManager.shared.actionExecutionLogs.append("✅ 动作回放完成")
    }
    
    @MainActor
    func deleteAction(id: UUID) {
        if let index = sessionEvents.firstIndex(where: { $0.id == id }) {
            let removed = sessionEvents.remove(at: index)
            AgentMonitorManager.shared.actionExecutionLogs.append("🗑 已删除动作: \(removed.elementText)")
        }
    }
    
    @MainActor
    func restartRecordingSession() {
        sessionEvents.removeAll()
        isPaused = false
        AgentMonitorManager.shared.actionExecutionLogs.append("🔄 已清空动作队列")
    }
    
    // MARK: - 数据保存与 AI 合成
    @MainActor
    func saveSessionAndContinue() async {
        guard !sessionEvents.isEmpty else { return }
        
        let finalDOM = sessionEvents.last(where: { !$0.domSummary.isEmpty })?.domSummary ?? ""
        let intent = currentUserIntent.isEmpty ? "连续操作任务 (\(sessionEvents.count)步)" : currentUserIntent
        
        let rawStepsJSON = sessionEvents.map { ev -> String in
            var dict: [String: Any] = ["action_type": ev.actionType, "target_id": ev.targetId, "element_desc": ev.elementText]
            if let val = ev.inputValue { dict["input_value"] = val }
            if let data = try? JSONSerialization.data(withJSONObject: dict), let str = String(data: data, encoding: .utf8) { return str }
            return "{}"
        }.joined(separator: ",\n")
        
        // [✨修改点3.4] 保存时标记为“人工带教”
        var record = WebCorpusRecord(
            id: UUID(),
            timestamp: Date(),
            userIntent: intent,
            beforeDOM: finalDOM,
            actionType: "sequence",
            targetId: "multi",
            inputValue: "[\n\(rawStepsJSON)\n]",
            groupName: "人工带教",
            isAutoGenerated: false
        )
        
        CorpusDatabase.shared.addRecord(record)
        AgentMonitorManager.shared.actionExecutionLogs.append("✅ [\(intent)] 已保存入库")
        
        self.sessionEvents.removeAll()
        self.currentUserIntent = ""
        self.isPaused = false
        
        Task {
            await synthesizeTrainingData(record: &record)
            DispatchQueue.main.async {
                if let idx = CorpusDatabase.shared.records.firstIndex(where: { $0.id == record.id }) {
                    CorpusDatabase.shared.records[idx] = record
                    CorpusDatabase.shared.save()
                }
            }
        }
    }
    
    private func synthesizeTrainingData(record: inout WebCorpusRecord) async {
        let cleanerID = UserDefaults.standard.string(forKey: "corpusCleanerProviderID") ?? ""
        let allProviders = AIConfigManager.shared.providers
        let specificProvider = allProviders.first(where: { $0.id.uuidString == cleanerID })
        let activeProvider = AIConfigManager.shared.activeProvider
        
        let prompt: String
        if record.actionType == "sequence" {
            let rawStepsJsonStr = record.inputValue ?? "[]"
            prompt = """
            你是一个 RPA 训练数据生成专家。用户刚刚在网页上执行了一个【连贯的系列任务】。
            【用户最终意图】: \(record.userIntent)
            【捕获的原始动作序列】:
            \(rawStepsJsonStr)
            【最终页面的 DOM 结构】:
            \(record.beforeDOM)
            
            【要求】
            1. 请结合动作序列，为整个任务流写出一段总体推理(thought)（限30字内）。
            2. 规范化为 Agent 可执行的 steps 数组。如果遇到连续多次输入同一个框，请优化保留最后一次即可。
            3. 必须输出合法 JSON，使用 ```json 包裹！
            ```json
            {
               "thought": "你的连贯推理",
               "steps": [
                   {"action_type": "hover/click/input/drag_drop", "target_id": "ID", "input_value": "值"}
               ]
            }
            ```
            """
        } else {
            var actionDict: [String: Any] = ["action_type": record.actionType, "target_id": record.targetId]
            if record.actionType == "input" { actionDict["input_value"] = record.inputValue ?? "" }
            let actionJsonData = (try? JSONSerialization.data(withJSONObject: actionDict)) ?? Data()
            let actionJsonStr = String(data: actionJsonData, encoding: .utf8) ?? "{}"
            
            prompt = """
            你是一个 RPA 训练数据生成专家。现在有一个用户在网页上执行了操作，我需要你基于他当时面临的【DOM元素列表】，为这个操作写出一段简短的【推理过程(thought)】。
            用户目的：\(record.userIntent)
            用户最终执行的动作：\(actionJsonStr)
            当时的DOM列表：\(record.beforeDOM)
            
            【要求】
            1. thought 必须简短直接（20字以内），解释为什么选择该元素。
            2. steps 原封不动使用上面提供的“用户最终执行的动作”。
            3. 请严格输出如下 JSON 格式，必须使用 ```json 包裹！不要解释！
            ```json
            {
               "thought": "你的简短推理",
               "steps": [\(actionJsonStr)]
            }
            ```
            """
        }
        
        let msg = LLMMessage(role: .user, text: prompt)
        do {
            let resultStr = try await LLMService.shared.generate(messages: [msg])
            var cleanJSONStr = ""
            if let start = resultStr.firstIndex(of: "{"), let end = resultStr.lastIndex(of: "}") {
                cleanJSONStr = String(resultStr[start...end])
            }
            
            if let data = cleanJSONStr.data(using: .utf8),
               let dict = try JSONSerialization.jsonObject(with: data) as? [String: Any] {
                record.synthesizedThought = dict["thought"] as? String ?? "⚠️ 模型未生成 thought"
                if let steps = dict["steps"], let stepsData = try? JSONSerialization.data(withJSONObject: steps) {
                    record.synthesizedStepsJSON = String(data: stepsData, encoding: .utf8)
                }
            }
        } catch {
            record.synthesizedThought = "❌ 接口报错"
            record.synthesizedStepsJSON = error.localizedDescription
        }
    }
    
    @MainActor
    func manualTranslate(recordId: UUID) async {
        let db = CorpusDatabase.shared
        guard let idx = db.records.firstIndex(where: { $0.id == recordId }) else { return }
        db.objectWillChange.send()
        db.records[idx].synthesizedThought = nil
        db.records[idx].synthesizedStepsJSON = nil
        var tempRecord = db.records[idx]
        await synthesizeTrainingData(record: &tempRecord)
        DispatchQueue.main.async {
            if let updateIdx = db.records.firstIndex(where: { $0.id == recordId }) {
                db.objectWillChange.send()
                db.records[updateIdx] = tempRecord
                db.save()
            }
        }
    }
}

// MARK: - 4. 语料可视化与人工介入管理面板
struct CorpusManagerView: View {
    @ObservedObject var database = CorpusDatabase.shared
    @ObservedObject var config = AIConfigManager.shared
    @State private var searchText = ""
    @State private var selectedGroup: String = "全部" // [✨修改点3.2]：分组筛选状态
    @State private var showGroupManager = false // [✨新增] 分组管理弹窗状态
    
    @AppStorage("corpusCleanerProviderID") var corpusCleanerID: String = ""
    @AppStorage("customCorpusGroupsData") var customGroupsData: Data = Data()
    
    // 动态提取所有现有分组
    var allGroups: [String] {
        var defaultGroups = ["默认分组", "人工带教", "AI 探索进化"]
        if let decoded = try? JSONDecoder().decode([String].self, from: customGroupsData) {
            defaultGroups.append(contentsOf: decoded)
        }
        let uniqueGroups = Set(database.records.map { $0.groupName })
        let merged = Set(defaultGroups).union(uniqueGroups)
        
        var final = Array(merged).sorted()
        final.removeAll { $0 == "全部" }
        final.insert("全部", at: 0) // 确保“全部”在最前面
        return final
    }
    
    var filteredRecords: [WebCorpusRecord] {
        var sorted = database.records.sorted(by: { $0.timestamp > $1.timestamp })
        if selectedGroup != "全部" {
            sorted = sorted.filter { $0.groupName == selectedGroup }
        }
        if !searchText.isEmpty {
            sorted = sorted.filter { $0.userIntent.localizedCaseInsensitiveContains(searchText) }
        }
        return sorted
    }
    
    var body: some View {
        VStack(spacing: 0) {
            HStack(spacing: 12) {
                Label("语料库", systemImage: "book.fill")
                    .font(.headline)
                    .foregroundColor(.purple)
                
                // [✨修改] 分组选择器 & 管理按钮
                HStack(spacing: 4) {
                    Picker("", selection: $selectedGroup) {
                        ForEach(allGroups, id: \.self) { group in
                            Text(group).tag(group)
                        }
                    }
                    .pickerStyle(.menu)
                    .frame(width: 120)
                    
                    Button(action: { showGroupManager = true }) {
                        Image(systemName: "folder.badge.gearshape")
                            .foregroundColor(.secondary)
                    }
                    .buttonStyle(.plain)
                    .help("管理语料分组")
                }
                
                HStack {
                    Image(systemName: "magnifyingglass").foregroundColor(.secondary)
                    TextField("搜索意图...", text: $searchText)
                        .textFieldStyle(.plain)
                        .frame(width: 100)
                }
                .padding(6)
                .background(Color(NSColor.controlBackgroundColor))
                .cornerRadius(8)
                .overlay(RoundedRectangle(cornerRadius: 8).stroke(Color.gray.opacity(0.2), lineWidth: 1))

                Divider().frame(height: 20)

                HStack(spacing: 4) {
                    Image(systemName: "sparkles").foregroundColor(.orange)
                    Picker("清洗模型:", selection: $corpusCleanerID) {
                        Text("跟随全局设置").tag("")
                        ForEach(config.providers) { provider in
                            Text(provider.name).tag(provider.id.uuidString)
                        }
                    }
                    .labelsHidden()
                    .controlSize(.small)
                    .frame(width: 130)
                }
                .help("为此处的手动转译和自动录制选择独立的高参数模型 (如 GPT-4/Claude)")

                Divider().frame(height: 20)
                
                Button(action: { createNewRecord() }) {
                    Label("新增", systemImage: "plus")
                        .controlSize(.small)
                }
                .buttonStyle(.bordered)
                .help("手动添加一条空语料")

                Button(action: { CorpusHUDManager.shared.toggleHUD() }) {
                    Label("录制", systemImage: "record.circle")
                        .foregroundColor(.red)
                        .controlSize(.small)
                }
                .buttonStyle(.bordered)
                .help("打开AI带教悬浮窗，支持 Safari、Chrome 和内置浏览器")

                Button(action: { exportCorpus() }) {
                    Label("导出 JSONL", systemImage: "square.and.arrow.up")
                        .controlSize(.small)
                }
                .buttonStyle(.bordered)
            }
            .padding(12)
            .background(.ultraThinMaterial)
            
            Divider()
            
            if filteredRecords.isEmpty {
                VStack(spacing: 20) {
                    Image(systemName: "tray.fill")
                        .font(.system(size: 40))
                        .foregroundColor(.gray.opacity(0.3))
                    Text(searchText.isEmpty ? (selectedGroup == "全部" ? "暂无录制语料，请开启带教模式进行录制" : "该分组下暂无语料") : "未找到匹配 \"\(searchText)\" 的语料")
                        .foregroundColor(.secondary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                List {
                    ForEach(filteredRecords) { record in
                        CorpusRecordRowView(recordId: record.id, availableGroups: allGroups)
                            .listRowSeparator(.visible)
                            .listRowInsets(EdgeInsets(top: 4, leading: 8, bottom: 4, trailing: 8))
                    }
                }
                .listStyle(.inset)
            }
            
            HStack {
                Text("共 \(filteredRecords.count) 条匹配语料")
                Spacer()
                if let selected = config.providers.first(where: { $0.id.uuidString == corpusCleanerID }) {
                    Text("当前清洗引擎: \(selected.name) (\(selected.modelName))")
                } else {
                    Text("当前清洗引擎: 默认全局配置 (\(config.activeProvider.modelName))")
                }
            }
            .font(.system(size: 10))
            .foregroundColor(.secondary)
            .padding(.horizontal, 12)
            .padding(.vertical, 6)
            .background(Color(NSColor.windowBackgroundColor))
        }
        .frame(minWidth: 880, minHeight: 500)
        .sheet(isPresented: $showGroupManager) {
            CorpusGroupManageSheet(customGroupsData: $customGroupsData, database: database)
        }
    }
    
    private func createNewRecord() {
        let group = selectedGroup == "全部" ? "默认分组" : selectedGroup
        let newRecord = WebCorpusRecord(
            id: UUID(),
            timestamp: Date(),
            userIntent: "新建手动语料",
            beforeDOM: "请在此输入现场 DOM 上下文...",
            actionType: "sequence",
            targetId: "multi",
            inputValue: "[]",
            groupName: group,
            isAutoGenerated: false
        )
        database.addRecord(newRecord)
    }
    
    private func exportCorpus() {
        let content = database.exportForFineTuning()
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.plainText]
        panel.nameFieldStringValue = "rpa_corpus_finetune_\(Date().formatted(date: .numeric, time: .omitted)).jsonl"
        
        if panel.runModal() == .OK, let url = panel.url {
            do {
                try content.write(to: url, atomically: true, encoding: .utf8)
            } catch {
                let alert = NSAlert()
                alert.messageText = "导出失败"
                alert.informativeText = error.localizedDescription
                alert.runModal()
            }
        }
    }
}

struct CorpusRecordRowView: View {
    let recordId: UUID
    var availableGroups: [String] = [] // [✨新增] 接收可用分组列表
    @ObservedObject var database = CorpusDatabase.shared
    
    @State private var isHovered = false
    @State private var showDetailSheet = false
    @State private var localIsTranslating = false
    
    private var currentRecord: WebCorpusRecord? {
        database.records.first(where: { $0.id == recordId })
    }
    
    var body: some View {
        guard let record = currentRecord else {
            return AnyView(EmptyView())
        }
        
        return AnyView(
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Text(record.userIntent)
                        .font(.system(size: 14, weight: .bold))
                        .lineLimit(1)
                    
                    // [✨修改点3.3] 增加视觉标签区分来源
                    if record.isAutoGenerated {
                        Text("🤖 AI 探索")
                            .font(.system(size: 9, weight: .bold))
                            .foregroundColor(.indigo)
                            .padding(.horizontal, 4).padding(.vertical, 2)
                            .background(Color.indigo.opacity(0.15))
                            .cornerRadius(4)
                    } else {
                        Text("👨‍🏫 人工带教")
                            .font(.system(size: 9, weight: .bold))
                            .foregroundColor(.teal)
                            .padding(.horizontal, 4).padding(.vertical, 2)
                            .background(Color.teal.opacity(0.15))
                            .cornerRadius(4)
                    }
                    
                    Spacer()
                    HStack(spacing: 12) {
                        Text("分组: \(record.groupName)")
                            .font(.caption)
                            .foregroundColor(.secondary)
                        Text("被调用: \(record.totalUsed)次")
                            .font(.caption)
                            .foregroundColor(.secondary)
                        Text(record.reliabilityStatus)
                            .font(.caption).bold()
                            .foregroundColor(getStatusColor(record.reliabilityStatus))
                            .padding(.horizontal, 6).padding(.vertical, 2)
                            .background(Color.gray.opacity(0.1))
                            .cornerRadius(4)
                    }
                }
                
                Text("录制时间: \(record.timestamp.formatted()) | 动作: \(record.actionType.uppercased()) | TargetID: \(record.targetId)")
                    .font(.caption2)
                    .foregroundColor(.secondary)
                
                if let thought = record.synthesizedThought, let steps = record.synthesizedStepsJSON {
                    VStack(alignment: .leading, spacing: 4) {
                        if !thought.contains("❌") {
                            Text("💡 \(thought)")
                                .font(.system(size: 11))
                                .foregroundColor(.purple)
                            Text(steps)
                                .font(.system(size: 11, design: .monospaced))
                                .foregroundColor(.blue)
                        } else {
                            HStack(spacing: 4) {
                                Image(systemName: "exclamationmark.triangle.fill")
                                Text(thought)
                            }
                            .font(.system(size: 11, weight: .bold))
                            .foregroundColor(.red)
                            
                            Text(steps)
                                .font(.system(size: 10))
                                .foregroundColor(.red.opacity(0.8))
                        }
                    }
                    .padding(8)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(thought.contains("❌") ? Color.red.opacity(0.05) : Color.blue.opacity(0.05))
                    .cornerRadius(6)
                } else {
                    HStack(spacing: 8) {
                        ProgressView()
                            .controlSize(.small)
                            .scaleEffect(0.6)
                        Text("AI 正在理解录制现场并生成推理...")
                            .font(.caption2)
                            .foregroundColor(.orange)
                            .italic()
                    }
                    .padding(8)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(Color.orange.opacity(0.05))
                    .cornerRadius(6)
                }
            }
            .padding(.vertical, 8)
            .padding(.horizontal, 8)
            .contentShape(Rectangle())
            .overlay(alignment: .topTrailing) {
                if isHovered, let record = currentRecord {
                    HStack(spacing: 12) {
                        Button(action: { showDetailSheet = true }) { Image(systemName: "doc.text.magnifyingglass").foregroundColor(.blue) }.buttonStyle(.plain)
                        
                        // [✨新增] 划入分组的下拉菜单
                        Menu {
                            Text("移动至分组...").font(.caption).foregroundColor(.secondary)
                            Divider()
                            ForEach(availableGroups.filter { $0 != "全部" && $0 != record.groupName }, id: \.self) { group in
                                Button(group) {
                                    if let idx = database.records.firstIndex(where: { $0.id == record.id }) {
                                        database.records[idx].groupName = group
                                        database.save()
                                    }
                                }
                            }
                        } label: {
                            Image(systemName: "folder.badge.plus").foregroundColor(.indigo)
                        }
                        .menuStyle(.borderlessButton)
                        .menuIndicator(.hidden)
                        .fixedSize()
                        .buttonStyle(.plain)
                        .help("划入其他分组")
                        
                        Button(action: {
                            withAnimation {
                                database.records.removeAll { $0.id == record.id }
                                database.save()
                            }
                        }) { Image(systemName: "trash").foregroundColor(.red) }.buttonStyle(.plain)
                    }
                    .padding(.horizontal, 10).padding(.vertical, 6)
                    .background(Capsule().fill(Color(NSColor.controlBackgroundColor).opacity(0.95)).shadow(color: .black.opacity(0.1), radius: 3, x: 0, y: 1))
                    .padding(.top, 4).padding(.trailing, 8)
                }
            }
            .onHover { hovering in withAnimation(.easeInOut(duration: 0.15)) { self.isHovered = hovering } }
            .sheet(isPresented: $showDetailSheet) { CorpusDetailView(record: record) }
        )
    }
    private func getStatusColor(_ status: String) -> Color {
        if status.contains("⚠️") { return .red }
        if status.contains("⭐️") { return .orange }
        if status.contains("✅") { return .green }
        return .secondary
    }
}

struct CorpusDetailView: View {
    @Environment(\.dismiss) var dismiss
    @State private var draftRecord: WebCorpusRecord
    @State private var isEditing: Bool = false
    
    init(record: WebCorpusRecord) { _draftRecord = State(initialValue: record) }
    
    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                Image(systemName: isEditing ? "pencil.and.outline" : "eye.circle.fill")
                    .font(.title2)
                    .foregroundColor(isEditing ? .orange : .blue)
                Text(isEditing ? "编辑语料记录" : "语料录制现场快照")
                    .font(.headline)
                Spacer()
                if isEditing {
                    Button("取消") {
                        if let original = CorpusDatabase.shared.records.first(where: { $0.id == draftRecord.id }) { draftRecord = original }
                        withAnimation(.easeInOut(duration: 0.2)) { isEditing = false }
                    }
                    .buttonStyle(.plain).foregroundColor(.gray).padding(.trailing, 8)
                    Button(action: saveChanges) { HStack(spacing: 4) { Image(systemName: "checkmark"); Text("保存修改") } }.buttonStyle(.borderedProminent).tint(.blue).controlSize(.small)
                } else {
                    Button(action: { withAnimation(.easeInOut(duration: 0.2)) { isEditing = true } }) { Image(systemName: "square.and.pencil").foregroundColor(.blue) }.buttonStyle(.plain).help("编辑此条语料").padding(.trailing, 8)
                    Button(action: { dismiss() }) { Image(systemName: "xmark.circle.fill").foregroundColor(.gray.opacity(0.6)).font(.title3) }.buttonStyle(.plain)
                }
            }
            .padding().background(Color(NSColor.windowBackgroundColor))
            Divider()
            ScrollView {
                VStack(alignment: .leading, spacing: 14) {
                    if isEditing { editForm() } else { readOnlyView() }
                }
                .padding()
            }
        }
        .frame(width: 600, height: 600)
    }
    
    private func saveChanges() {
        let db = CorpusDatabase.shared
        if let idx = db.records.firstIndex(where: { $0.id == draftRecord.id }) {
            db.objectWillChange.send()
            db.records[idx] = draftRecord
            db.save()
            withAnimation(.easeInOut(duration: 0.2)) { isEditing = false }
        }
    }
    
    @ViewBuilder
    private func editForm() -> some View {
        VStack(alignment: .leading, spacing: 16) {
            DarwinDataEditor(record: $draftRecord)
            VStack(alignment: .leading, spacing: 6) {
                Text("目标意图 (User Intent)").font(.caption).foregroundColor(.secondary)
                TextField("请输入用户操作意图", text: $draftRecord.userIntent).textFieldStyle(.roundedBorder)
            }
            HStack(spacing: 16) {
                VStack(alignment: .leading, spacing: 6) {
                    Text("交互动作 (Action Type)").font(.caption).foregroundColor(.secondary)
                    TextField("例如: click, input, sequence", text: $draftRecord.actionType).textFieldStyle(.roundedBorder)
                }
                VStack(alignment: .leading, spacing: 6) {
                    Text("目标 ID (Target ID)").font(.caption).foregroundColor(.secondary)
                    TextField("目标元素ID", text: $draftRecord.targetId).textFieldStyle(.roundedBorder)
                }
            }
            VStack(alignment: .leading, spacing: 6) {
                Text("输入内容或序列 (Input Value / Sequence JSON)").font(.caption).foregroundColor(.secondary)
                JSCodeEditor(text: Binding(get: { draftRecord.inputValue ?? "" }, set: { draftRecord.inputValue = $0.isEmpty ? nil : $0 }))
                .font(.system(size: 12, design: .monospaced)).frame(minHeight: 80).padding(4).background(Color(NSColor.textBackgroundColor)).overlay(RoundedRectangle(cornerRadius: 6).stroke(Color.gray.opacity(0.2)))
            }
            Divider()
            VStack(alignment: .leading, spacing: 6) {
                Text("AI 推理过程 (Thought)").font(.caption).foregroundColor(.secondary)
                JSCodeEditor(text: Binding(get: { draftRecord.synthesizedThought ?? "" }, set: { draftRecord.synthesizedThought = $0.isEmpty ? nil : $0 })).textFieldStyle(.roundedBorder)
            }
            VStack(alignment: .leading, spacing: 6) {
                Text("可执行步骤 (Steps JSON) ⚠️ 必须是合法的 JSON").font(.caption).foregroundColor(.secondary)
                JSCodeEditor(text: Binding(get: { draftRecord.synthesizedStepsJSON ?? "" }, set: { draftRecord.synthesizedStepsJSON = $0.isEmpty ? nil : $0 }))
                .font(.system(size: 12, design: .monospaced)).frame(minHeight: 120).padding(4).background(Color(NSColor.textBackgroundColor)).overlay(RoundedRectangle(cornerRadius: 6).stroke(Color.gray.opacity(0.2)))
            }
            VStack(alignment: .leading, spacing: 6) {
                Text("现场 DOM 结构 (Prompt Context)").font(.caption).foregroundColor(.secondary)
                JSCodeEditor(text: $draftRecord.beforeDOM)
                    .font(.system(size: 11, design: .monospaced)).frame(minHeight: 100).padding(4).background(Color(NSColor.textBackgroundColor)).overlay(RoundedRectangle(cornerRadius: 6).stroke(Color.gray.opacity(0.2)))
            }
        }.padding(.top, 4)
    }
    
    @ViewBuilder
    private func readOnlyView() -> some View {
        Group {
            detailRow(title: "目标意图", content: draftRecord.userIntent)
            detailRow(title: "交互动作", content: draftRecord.actionType.uppercased())
            detailRow(title: "目标 ID", content: "[\(draftRecord.targetId)]")
            if let val = draftRecord.inputValue, !val.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    Text("输入内容:").font(.system(size: 12, weight: .bold)).foregroundColor(.secondary)
                    Text(val).font(.system(size: 11, design: .monospaced)).foregroundColor(.primary).padding(8).frame(maxWidth: .infinity, alignment: .leading).background(Color.black.opacity(0.04)).cornerRadius(6)
                }
            }
            if let thought = draftRecord.synthesizedThought { detailRow(title: "AI 推理", content: "💡 \(thought)") }
            if let steps = draftRecord.synthesizedStepsJSON {
                VStack(alignment: .leading, spacing: 4) {
                    Text("执行步骤 JSON:").font(.system(size: 12, weight: .bold)).foregroundColor(.secondary).padding(.top, 4)
                    Text(steps).font(.system(size: 11, design: .monospaced)).foregroundColor(.blue).padding(8).frame(maxWidth: .infinity, alignment: .leading).background(Color.blue.opacity(0.05)).cornerRadius(6)
                }
            }
        }
        Divider().padding(.vertical, 4)
        Text("📋 录制瞬间的网页 DOM 精简树:").font(.system(size: 12, weight: .bold)).foregroundColor(.secondary)
        Text(draftRecord.beforeDOM).font(.system(size: 11, design: .monospaced)).foregroundColor(.primary).padding(12).frame(maxWidth: .infinity, alignment: .leading).background(Color.black.opacity(0.05)).cornerRadius(6).overlay(RoundedRectangle(cornerRadius: 6).stroke(Color.gray.opacity(0.2)))
    }
    
    private func detailRow(title: String, content: String) -> some View {
        HStack(alignment: .top) {
            Text(title + ":").font(.system(size: 12, weight: .bold)).foregroundColor(.secondary).frame(width: 85, alignment: .leading)
            Text(content).font(.system(size: 13)).foregroundColor(.primary)
        }
    }
}

struct DarwinDataEditor: View {
    @Binding var record: WebCorpusRecord
    var body: some View {
        GroupBox("📊 达尔文机制数据干预 (人工调权)") {
            HStack(spacing: 24) {
                HStack { Text("✅ 正确次数:").font(.caption).foregroundColor(.secondary); Stepper(value: $record.successCount, in: 0...99999) { Text("\(record.successCount)").font(.system(.body, design: .monospaced)).foregroundColor(.green).frame(minWidth: 35, alignment: .leading) } }
                HStack { Text("❌ 错误次数:").font(.caption).foregroundColor(.secondary); Stepper(value: $record.failCount, in: 0...99999) { Text("\(record.failCount)").font(.system(.body, design: .monospaced)).foregroundColor(.red).frame(minWidth: 35, alignment: .leading) } }
                Spacer()
                VStack(alignment: .trailing, spacing: 2) {
                    Text("总被调次数: \(record.totalUsed)").font(.caption).bold().foregroundColor(.primary)
                    Text("当前可靠性: \(record.reliabilityStatus)").font(.caption2).foregroundColor(record.reliabilityStatus.contains("高") ? .green : (record.reliabilityStatus.contains("低") ? .red : .orange))
                }.padding(.horizontal, 10).padding(.vertical, 6).background(Color.black.opacity(0.05)).cornerRadius(6)
            }.padding(8)
        }
    }
}

class CorpusManagerWindowController: NSWindowController {
    static var sharedController: CorpusManagerWindowController?
    @MainActor
    static func showWindow() {
        if sharedController == nil {
            let hostingController = NSHostingController(rootView: CorpusManagerView())
            let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 750, height: 550), styleMask: [.titled, .closable, .resizable, .miniaturizable, .fullSizeContentView], backing: .buffered, defer: false)
            window.title = "AI 动作经验库 (本地 RAG)"
            window.minSize = NSSize(width: 600, height: 400)
            window.center()
            window.isReleasedWhenClosed = false
            window.contentViewController = hostingController
            sharedController = CorpusManagerWindowController(window: window)
        }
        if let window = sharedController?.window {
            if window.isMiniaturized { window.deminiaturize(nil) }
            window.makeKeyAndOrderFront(nil)
        }
        NSApp.activate(ignoringOtherApps: true)
    }
}

// MARK: - 悬浮窗 HUD 组件 (更换为普通 NSWindow)
class HUDWindow: NSWindow {
    // 允许普通 Window 获取焦点，保证内部的 TextField 可以正常输入
    override var canBecomeKey: Bool { return true }
    override var canBecomeMain: Bool { return false }
}

class CorpusHUDManager {
    static let shared = CorpusHUDManager()
    private var window: HUDWindow? // 从 panel 替换为 window
    
    // 保持内外尺寸约束绝对一致，防止缩放产生的裁切发虚感
    private let expandedSize = NSSize(width: 400, height: 520)
    private let collapsedSize = NSSize(width: 170, height: 42)
    
    func toggleHUD() {
        if window?.isVisible == true { hideHUD() } else { showHUD() }
    }
    
    func showHUD() {
        if window == nil {
            // 使用普通 NSWindow，仅保留 borderless 实现无边框 UI
            let newWindow = HUDWindow(
                contentRect: NSRect(origin: .zero, size: collapsedSize),
                styleMask: [.borderless],
                backing: .buffered,
                defer: false
            )
            
            newWindow.level = .floating // 依然保持悬浮在最顶层
            newWindow.backgroundColor = .clear // 保持背景透明
            newWindow.isOpaque = false
            newWindow.hasShadow = true // 仅依赖系统级物理阴影，极其干净
            newWindow.isMovableByWindowBackground = true // 允许拖拽背景移动
            newWindow.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
            
            let host = NSHostingView(rootView: CorpusRecordingHUD())
            host.wantsLayer = true
            host.layer?.backgroundColor = NSColor.clear.cgColor
            
            newWindow.contentView = host
            self.window = newWindow
        }
        
        WebCorpusManager.shared.isPaused = true
        updatePanelFrame(animate: false)
        window?.orderFrontRegardless()
    }
    
    func updatePanelFrame(animate: Bool = true) {
        guard let window = window, let screen = NSScreen.main else { return }
        
        // 💡 完美读取静态状态：判断当前是收起还是展开
        let isExpanded = WebCorpusManager.shared.isRecordingMode && !CorpusRecordingHUD.globalIsCollapsedOverride
        let targetSize = isExpanded ? expandedSize : collapsedSize
        let screenFrame = screen.visibleFrame
        
        // 绝对右上角锚定
        let targetX = screenFrame.maxX - targetSize.width - 20
        let targetY = screenFrame.maxY - targetSize.height - 20
        let newFrame = NSRect(origin: CGPoint(x: targetX, y: targetY), size: targetSize)
        
        if animate {
            NSAnimationContext.runAnimationGroup { context in
                // 🚀 使用最干净的系统 easeInEaseOut 代替贝塞尔弹簧效果，消灭卡顿和拖影
                context.duration = 0.25
                context.timingFunction = CAMediaTimingFunction(name: .easeInEaseOut)
                window.animator().setFrame(newFrame, display: true)
            }
        } else {
            window.setFrame(newFrame, display: true)
        }
    }
    
    func hideHUD() {
        if WebCorpusManager.shared.isRecordingMode { WebCorpusManager.shared.isRecordingMode = false }
        if let window = window {
            NSAnimationContext.runAnimationGroup { context in
                context.duration = 0.25
                window.animator().alphaValue = 0
            } completionHandler: {
                self.window?.orderOut(nil)
                self.window?.alphaValue = 1.0
            }
        }
    }
}

// MARK: - [✨带教面板终极升级] (强制深色模式，绝佳高对比度护眼版 + 丝滑缩放动画)
struct CorpusRecordingHUD: View {
    @ObservedObject var corpusManager = WebCorpusManager.shared
    @State private var pulseStage: CGFloat = 0.0
    @State private var glowRotation: Double = 0
    @State private var lastActionLog: String = "快捷键 ⌥⌘R 启停"
    @State private var logHighlight: Bool = false
    @State private var selectedEventId: UUID? = nil
    
    // 供 Manager 计算 Frame 使用
    @AppStorage("hudIsCollapsedOverride") static var globalIsCollapsedOverride: Bool = false
    @State private var isCollapsedOverride: Bool = CorpusRecordingHUD.globalIsCollapsedOverride

    // 1. 抽离状态灯的复杂三元运算推断
    private var isPaused: Bool { corpusManager.isPaused }
    private var indicatorColor: Color {
        isPaused ? Color.orange : (pulseStage > 0.5 ? Color.red : Color.darkRed)
    }
    private var indicatorShadow: Color { isPaused ? .orange : .red }
    private var indicatorText: String { isPaused ? "PAUSED" : "REC STEP" }
    private var indicatorOpacity: Double { isPaused ? 1.0 : (0.7 + Double(pulseStage) * 0.3) }
    private var indicatorBg: Color { isPaused ? Color.orange.opacity(0.8) : Color.red.opacity(0.8) }
    
    // 2. 抽离底部控制栏的复杂颜色推断
    private var hasSteps: Bool { !corpusManager.sessionEvents.isEmpty }
    private var playPauseBg: Color { isPaused ? Color.green.opacity(0.8) : Color.orange.opacity(0.8) }
    private var playAllBg: Color { hasSteps ? Color.purple.opacity(0.8) : Color.white.opacity(0.1) }
    private var playAllFg: Color { hasSteps ? .white : .white.opacity(0.4) }
    private var clearBg: Color { hasSteps ? Color.red.opacity(0.8) : Color.white.opacity(0.1) }
    private var clearFg: Color { hasSteps ? .white : .white.opacity(0.4) }
    private var saveText: String { hasSteps ? "保存 (\(corpusManager.sessionEvents.count)步)" : "等待中" }
    private var saveBg: Color { hasSteps ? Color.blue : Color.white.opacity(0.1) }
    private var saveFg: Color { hasSteps ? .white : .white.opacity(0.4) }
    private var saveShadow: Color { hasSteps ? Color.blue.opacity(0.4) : .clear }

    var body: some View {
        mainContent
            .background(backgroundEffectView)
            .clipShape(RoundedRectangle(cornerRadius: 16, style: .continuous))
            .overlay(RoundedRectangle(cornerRadius: 16, style: .continuous).strokeBorder(Color.white.opacity(0.15), lineWidth: 1))
            // 🚀 核心：彻底剥离 SwiftUI 内部的 `.shadow(...)`，交由 NSWindow 管理系统级物理阴影，解决变大变小时的残影问题
            .environment(\.colorScheme, .dark)
            .onReceive(AgentMonitorManager.shared.$actionExecutionLogs, perform: handleNewLog)
            .onChange(of: corpusManager.isRecordingMode) { _ in CorpusHUDManager.shared.updatePanelFrame() }
            .onChange(of: isCollapsedOverride) { _, newValue in
                CorpusRecordingHUD.globalIsCollapsedOverride = newValue
                CorpusHUDManager.shared.updatePanelFrame(animate: true)
            }
    }
    
    @ViewBuilder private var mainContent: some View {
        // 🚀 [核心优化] 统一改为透明度溶解，配合窗口边界伸缩，取消导致卡顿发虚的 scale
        ZStack(alignment: .topTrailing) {
            if corpusManager.isRecordingMode && !isCollapsedOverride {
                expandedRecordingView
                    .transition(.opacity)
            } else {
                collapsedView
                    .transition(.opacity)
            }
        }
        // 使用匹配 NSWindow 的过渡时间，最顺滑跟手
        .animation(.easeInOut(duration: 0.25), value: isCollapsedOverride)
        .animation(.easeInOut(duration: 0.25), value: corpusManager.isRecordingMode)
    }
    
    @ViewBuilder private var backgroundEffectView: some View {
        ZStack {
            // 采用高级 IDE 的深灰护眼色，彻底隔绝浅色网页底色干扰，文字对比度极高
            Color(red: 0.12, green: 0.12, blue: 0.14)
            
            if corpusManager.isRecordingMode && !corpusManager.isPaused {
                RoundedRectangle(cornerRadius: 16)
                    .stroke(AngularGradient(colors: [.red, .orange, .clear, .orange, .red], center: .center, angle: .degrees(glowRotation)), lineWidth: 3)
            }
        }
    }
    
    private var expandedRecordingView: some View {
        VStack(alignment: .leading, spacing: 10) {
            topBarView
            
            TextField("在此备注当前操作意图...", text: $corpusManager.currentUserIntent)
                .textFieldStyle(.plain)
                .padding(9)
                .background(Color.white.opacity(0.1)) // 使用微白勾勒输入框底色
                .cornerRadius(8)
                .font(.system(size: 12))
                .foregroundColor(.white)
            
            HStack(spacing: 4) {
                Image(systemName: corpusManager.isPaused ? "pause.circle.fill" : "bolt.horizontal.circle.fill")
                    .foregroundColor(logHighlight ? .orange : .white.opacity(0.6))
                Text(lastActionLog).font(.system(size: 10, design: .monospaced))
                    .foregroundColor(logHighlight ? .orange : .white.opacity(0.7)).lineLimit(1)
            }.padding(.horizontal, 4).id(lastActionLog)
            
            eventsScrollView
            
            bottomControlBar
        }
        .padding(14)
        .frame(width: 400, height: 520) // 完全对齐 HUDManager 中设定的物理尺寸
    }
    
    private var topBarView: some View {
        HStack {
            RecordingIndicatorLight(isPaused: isPaused)
            
            Spacer()
            
            Button(action: { withAnimation { isCollapsedOverride = true } }) {
                Image(systemName: "arrow.down.right.and.arrow.up.left").foregroundColor(.white.opacity(0.8)).font(.system(size: 12, weight: .bold))
            }.buttonStyle(.plain).padding(.trailing, 6).help("缩小面板")
            
            Button(action: { corpusManager.closeRecording() }) {
                Image(systemName: "xmark.circle.fill").foregroundColor(.white.opacity(0.8)).font(.system(size: 14))
            }.buttonStyle(.plain)
        }
    }
    
    private var eventsScrollView: some View {
        ScrollViewReader { proxy in
            ScrollView {
                LazyVStack(spacing: 6) {
                    ForEach(corpusManager.sessionEvents) { event in
                        CorpusEventRowView(
                            event: safeBinding(for: event),
                            isPlaying: corpusManager.playingEventId == event.id,
                            isSelected: selectedEventId == event.id,
                            onPlay: { Task { await corpusManager.playbackAction(event: event) } },
                            onDelete: {
                                if selectedEventId == event.id { selectedEventId = nil }
                                NSApp.keyWindow?.makeFirstResponder(nil)
                                withAnimation { corpusManager.deleteAction(id: event.id) }
                            }
                        )
                        .onTapGesture { selectedEventId = event.id }
                        .id(event.id)
                    }
                }
                .padding(.horizontal, 4)
                .padding(.vertical, 4)
            }
            .frame(maxHeight: 350)
            .background(Color.black.opacity(0.3)) // 列表底槽加深，反衬出卡片
            .cornerRadius(8)
            .onChange(of: corpusManager.sessionEvents.count) { _, _ in
                if let lastId = corpusManager.sessionEvents.last?.id {
                    withAnimation { proxy.scrollTo(lastId, anchor: .bottom) }
                }
            }
            .onChange(of: corpusManager.playingEventId) { _, newId in
                if let playId = newId {
                    withAnimation { proxy.scrollTo(playId, anchor: .center) }
                }
            }
        }
    }
    
    private var bottomControlBar: some View {
        HStack(spacing: 8) {
            Button(action: { withAnimation(.easeInOut(duration: 0.2)) { corpusManager.isPaused.toggle() } }) {
                HStack(spacing: 4) { Image(systemName: isPaused ? "play.fill" : "pause.fill") }
                .font(.system(size: 10, weight: .bold)).frame(width: 24, height: 24)
                .background(playPauseBg)
                .foregroundColor(.white).clipShape(Circle())
            }.buttonStyle(.plain).help(isPaused ? "继续录制" : "暂停捕获")
            
            Button(action: { withAnimation { corpusManager.addWaitAction() } }) {
                Image(systemName: "timer")
                .font(.system(size: 11, weight: .bold)).frame(width: 24, height: 24)
                .background(Color.cyan.opacity(0.8)).foregroundColor(.white).clipShape(Circle())
            }.buttonStyle(.plain).help("插入1秒等待节点")
            
            Button(action: { Task { await corpusManager.playAllActions() } }) {
                HStack(spacing: 4) { Image(systemName: "play.rectangle.fill"); Text("回放") }
                .font(.system(size: 10, weight: .bold)).padding(.horizontal, 8).padding(.vertical, 5)
                .background(playAllBg)
                .foregroundColor(playAllFg).clipShape(Capsule())
            }.buttonStyle(.plain).disabled(!hasSteps || corpusManager.playingEventId != nil).help("可视化按序回放所有动作")
            
            Button(action: { corpusManager.stopRecording() }) {
                HStack(spacing: 4) { Image(systemName: "stop.fill") }
                .font(.system(size: 10, weight: .bold)).padding(.horizontal, 6).padding(.vertical, 5)
                .background(Color.white.opacity(0.15)).foregroundColor(.white).clipShape(Circle())
            }.buttonStyle(.plain).help("停止录制并关闭")
            
            Button(action: { withAnimation { corpusManager.restartRecordingSession() } }) {
                HStack(spacing: 4) { Image(systemName: "trash.fill") }
                .font(.system(size: 10, weight: .bold)).padding(.horizontal, 6).padding(.vertical, 5)
                .background(clearBg)
                .foregroundColor(clearFg).clipShape(Circle())
            }.buttonStyle(.plain).disabled(!hasSteps).help("清空当前已录制的动作流")
            
            Spacer()
            
            Button(action: { Task { await corpusManager.saveSessionAndContinue() } }) {
                Text(saveText)
                    .font(.system(size: 11, weight: .bold)).padding(.horizontal, 10).padding(.vertical, 6)
                    .background(Capsule().fill(saveBg))
                    .foregroundColor(saveFg)
                    .shadow(color: saveShadow, radius: 4)
            }.buttonStyle(.plain).disabled(!hasSteps)
        }
    }
    
    private func safeBinding(for event: WebCorpusManager.RawSessionEvent) -> Binding<WebCorpusManager.RawSessionEvent> {
        Binding(
            get: {
                if let index = corpusManager.sessionEvents.firstIndex(where: { $0.id == event.id }) { return corpusManager.sessionEvents[index] }
                return event
            },
            set: { newValue in
                if let index = corpusManager.sessionEvents.firstIndex(where: { $0.id == event.id }) { corpusManager.sessionEvents[index] = newValue }
            }
        )
    }
    
    private var collapsedView: some View {
        HStack(spacing: 12) {
            Button(action: { withAnimation { corpusManager.isPaused.toggle() } }) {
                Circle().fill(isPaused ? Color.green : Color.orange)
                    .frame(width: 16, height: 16).overlay(Image(systemName: isPaused ? "play.fill" : "pause.fill").font(.system(size: 8, weight: .bold)).foregroundColor(.white))
            }.buttonStyle(.plain)
            
            Spacer()
            
            Button(action: {
                if !corpusManager.isRecordingMode { corpusManager.isRecordingMode = true }
                withAnimation { isCollapsedOverride = false }
            }) {
                // 蓝绿色在暗色底上可见度最高
                Image(systemName: "arrow.up.left.and.arrow.down.right").foregroundColor(.cyan).font(.system(size: 12, weight: .bold))
            }.buttonStyle(.plain)
            
            Button(action: { corpusManager.closeRecording() }) {
                Image(systemName: "xmark.circle.fill").foregroundColor(.red.opacity(0.9)).font(.system(size: 14))
            }.buttonStyle(.plain)
        }
        .padding(.horizontal, 12)
        .frame(width: 170, height: 42) // 完全对齐 HUDManager 物理尺寸
    }
    
    private func setupAnimations() {
        withAnimation(.linear(duration: 3).repeatForever(autoreverses: false)) { glowRotation = 360 }
        withAnimation(.easeInOut(duration: 0.75).repeatForever(autoreverses: true)) { pulseStage = 1.0 }
    }
    
    private func handleNewLog(_ logs: [String]) {
        if let last = logs.last {
            self.lastActionLog = last
            withAnimation(.none) { self.logHighlight = true }
            withAnimation(.easeOut(duration: 1.5).delay(1.0)) { self.logHighlight = false }
        }
    }
}

// MARK: - 单行组件 (全面适配深色高对比度)
struct CorpusEventRowView: View {
    @Binding var event: WebCorpusManager.RawSessionEvent
    var isPlaying: Bool
    var isSelected: Bool
    var onPlay: () -> Void
    var onDelete: () -> Void
    
    // 💡 全部替换为基于白色的高透明度背景，确保在深灰底色上轮廓分明
    private var rowBgColor: Color {
        if isPlaying { return Color.green.opacity(0.25) }
        if isSelected { return Color.blue.opacity(0.25) }
        return Color.white.opacity(0.08)
    }
    
    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(spacing: 8) {
                Text("[\(event.actionType)]")
                    .font(.system(size: 10, weight: .bold))
                    .foregroundColor(.cyan) // 暗色模式下 Cyan 比 Blue 更亮眼
                    .frame(width: 60, alignment: .leading)
                
                HStack(spacing: 2) {
                    Text("ID:")
                        .font(.system(size: 9, weight: .bold))
                        .foregroundColor(.white.opacity(0.7))
                    TextField("空", text: $event.targetId)
                        .font(.system(size: 9, weight: .bold))
                        .foregroundColor(.white)
                        .textFieldStyle(.plain)
                }
                .padding(.horizontal, 4).padding(.vertical, 1)
                .frame(width: 80, alignment: .leading)
                .background(Color.white.opacity(0.15)) // ID 框高亮提底
                .cornerRadius(4)
                
                TextField("元素描述", text: $event.elementText)
                    .font(.system(size: 11))
                    .foregroundColor(.white) // 绝对强制白色，覆盖系统的 primary 黑色
                    .textFieldStyle(.plain)
                
                Spacer()
                
                if isPlaying {
                    Image(systemName: "play.circle.fill").foregroundColor(.green)
                } else {
                    Button(action: onPlay) { Image(systemName: "play.fill").font(.system(size: 10)).foregroundColor(.white.opacity(0.6)) }.buttonStyle(.plain)
                }
                Button(action: onDelete) { Image(systemName: "trash").font(.system(size: 10)).foregroundColor(.red.opacity(0.8)) }.buttonStyle(.plain).padding(.leading, 4)
            }
            
            if event.actionType == "input" || event.actionType == "wait" {
                HStack {
                    Image(systemName: "arrow.turn.down.right").foregroundColor(.white.opacity(0.5)).font(.system(size: 10)).frame(width: 60, alignment: .trailing)
                    TextField("输入值/时间", text: Binding(
                        get: { event.inputValue ?? "" },
                        set: { event.inputValue = $0 }
                    ))
                    .font(.system(size: 11, design: .monospaced))
                    .foregroundColor(.orange)
                    .textFieldStyle(.plain)
                }
            }
        }
        .padding(.horizontal, 8).padding(.vertical, 6)
        .background(RoundedRectangle(cornerRadius: 6).fill(rowBgColor))
    }
}

// [✨新增] 将该结构体贴在 AICorpusManager.swift 的底部
struct CorpusGroupManageSheet: View {
    @Binding var customGroupsData: Data
    @ObservedObject var database: CorpusDatabase
    @Environment(\.presentationMode) var presentationMode
    
    @State private var groups: [String] = []
    @State private var newGroupName: String = ""
    @State private var editingGroup: String? = nil
    @State private var editName: String = ""
    
    let protectedGroups = ["默认分组", "人工带教", "AI 探索进化"]
    
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("管理语料分组").font(.headline)
            
            HStack {
                TextField("输入新分组名称...", text: $newGroupName)
                    .textFieldStyle(.roundedBorder)
                Button("添加") {
                    let trimmed = newGroupName.trimmingCharacters(in: .whitespacesAndNewlines)
                    if !trimmed.isEmpty && !groups.contains(trimmed) && !protectedGroups.contains(trimmed) {
                        groups.append(trimmed)
                        saveGroups()
                        newGroupName = ""
                    }
                }
                .disabled(newGroupName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                .buttonStyle(.borderedProminent)
            }
            
            List {
                Section(header: Text("系统内置分组").font(.caption).foregroundColor(.secondary)) {
                    ForEach(protectedGroups, id: \.self) { group in
                        Text(group).foregroundColor(.secondary)
                    }
                }
                
                Section(header: Text("自定义分组").font(.caption).foregroundColor(.secondary)) {
                    ForEach(groups, id: \.self) { group in
                        HStack {
                            if editingGroup == group {
                                TextField("名称", text: $editName)
                                    .textFieldStyle(.roundedBorder)
                                Button("保存") {
                                    renameGroup(oldName: group, newName: editName)
                                    editingGroup = nil
                                }.buttonStyle(.borderedProminent).controlSize(.small)
                            } else {
                                Text(group)
                                Spacer()
                                Button(action: { editingGroup = group; editName = group }) { Image(systemName: "pencil").foregroundColor(.blue) }.buttonStyle(.plain)
                                Button(action: { deleteGroup(group) }) { Image(systemName: "trash").foregroundColor(.red) }.buttonStyle(.plain).padding(.leading, 8)
                            }
                        }
                    }
                }
            }
            .listStyle(.bordered)
            .frame(minHeight: 200)
            
            HStack {
                Spacer()
                Button("完成") { presentationMode.wrappedValue.dismiss() }.keyboardShortcut(.defaultAction)
            }
        }
        .padding()
        .frame(width: 400, height: 450)
        .onAppear { loadGroups() }
    }
    
    private func loadGroups() {
        if let decoded = try? JSONDecoder().decode([String].self, from: customGroupsData) {
            groups = decoded.filter { !protectedGroups.contains($0) }
        }
    }
    
    private func saveGroups() {
        if let encoded = try? JSONEncoder().encode(groups) {
            customGroupsData = encoded
        }
    }
    
    private func deleteGroup(_ name: String) {
        groups.removeAll { $0 == name }
        saveGroups()
    }
    
    private func renameGroup(oldName: String, newName: String) {
        let trimmed = newName.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, !groups.contains(trimmed), !protectedGroups.contains(trimmed) else { return }
        if let idx = groups.firstIndex(of: oldName) {
            groups[idx] = trimmed
            saveGroups()
            // 同步修改数据库中关联的语料
            for i in 0..<database.records.count {
                if database.records[i].groupName == oldName {
                    database.records[i].groupName = trimmed
                }
            }
            database.save()
        }
    }
}

// MARK: - [✨新增] 独立状态组件：发光边框 (解决 TextField 狂刷布局的 Bug)
struct RecordingGlowBorder: View {
    var isPaused: Bool
    @State private var glowRotation: Double = 0
    
    var body: some View {
        ZStack {
            if !isPaused {
                RoundedRectangle(cornerRadius: 16)
                    .stroke(AngularGradient(colors: [.red, .orange, .clear, .orange, .red], center: .center, angle: .degrees(glowRotation)), lineWidth: 3)
                    .onAppear {
                        withAnimation(.linear(duration: 3).repeatForever(autoreverses: false)) { glowRotation = 360 }
                    }
            }
        }
    }
}

// MARK: - [✨修复] 状态指示组件：解决因动画强制刷新导致的 TextField 抖动和闪退 Bug
struct RecordingIndicatorLight: View {
    var isPaused: Bool
    @State private var isPulsing: Bool = false
    
    var body: some View {
        HStack(spacing: 6) {
            Circle()
                .fill(isPaused ? Color.orange : Color.red)
                .frame(width: 8, height: 8)
                .shadow(color: isPaused ? .orange : .red, radius: isPulsing && !isPaused ? 4 : 0)
            
            Text(isPaused ? "PAUSED" : "REC STEP")
                .font(.system(size: 10, weight: .black))
                .foregroundColor(.white)
                .opacity(isPaused ? 1.0 : (isPulsing ? 1.0 : 0.6))
        }
        .padding(.horizontal, 10).padding(.vertical, 4)
        .background(isPaused ? Color.orange.opacity(0.8) : Color.red.opacity(0.8))
        .clipShape(Capsule())
        // ⚠️ 同样加入 fixedSize，阻断重新计算
        .fixedSize()
        .onAppear {
            withAnimation(.easeInOut(duration: 0.8).repeatForever(autoreverses: true)) {
                isPulsing = true
            }
        }
    }
}

extension Color {
    static let darkRed = Color(red: 0.5, green: 0, blue: 0)
}
